import { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import PageContainer from '../../components/layout/PageContainer';
import Button from '../../components/common/Button';
import ActionModal from '../../components/common/ActionModal';
import { subscriptionApi } from '../../api/actPulse.Api';
import { useSubscriptionStore } from '../../store/subscription.store';
import { formatDate } from '../../utils/formatDate';
import BillingWorkspace from './BillingWorkspace';

const panel='rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900';
const select='mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100';
const labels={live_monitoring:'Live monitoring and basic dashboard',fuel_records:'Manual fuel readings and refills',fuel_estimates:'Fuel estimates',fuel_costs_reconciliation:'Fuel costs and reconciliation',maintenance:'Maintenance planning and service history',advanced_reports:'Advanced operational reports',pdf_export:'PDF export',fleet_analytics:'Fleet analytics'};
const cycles=[['MONTHLY','Monthly','monthly_price'],['QUARTERLY','Quarterly','quarterly_price'],['ANNUALLY','Annually','annual_price']];
export default function SubscriptionControl() {
  const {status,refresh}=useSubscriptionStore();
  const location=useLocation();
  const [plans,setPlans]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState(null),[cycle,setCycle]=useState('MONTHLY'),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[requestKey,setRequestKey]=useState('');
  useEffect(()=>{subscriptionApi.plans().then(({data})=>setPlans(data)).catch(err=>setError(err?.response?.data?.message||'Could not load plans.')).finally(()=>setLoading(false));},[]);
  const choice=(plan)=>{setSelected(plan);setCycle(status?.billingCycle||'MONTHLY');setConfirm(false);setRequestKey(crypto.randomUUID());setError('');};
  const submit=async(event)=>{event.preventDefault();if(!confirm){setConfirm(true);return;}setBusy(true);setError('');try{const result=await subscriptionApi.select({planCode:selected.code,billingCycle:cycle,idempotencyKey:requestKey});await refresh();setNotice(result.data.trialStarted?'Your 14-day trial has started. An invoice is available below.':'Plan order and invoice created. Payment approval is required for paid access.');setSelected(null);setConfirm(false);setRequestKey('');window.dispatchEvent(new Event('subscription:access-changed'));window.dispatchEvent(new Event('billing:changed'));}catch(err){const data=err?.response?.data;setError(typeof data?.message==='string'?data.message:'Could not select plan.');}finally{setBusy(false);}};
  const days=status?.state==='TRIALING'?Math.max(0,Math.ceil((new Date(status.trialEndsAt)-new Date())/86400000)):null;
  return <PageContainer title="Subscription Control" subtitle="Choose a plan, review limits and manage manual billing">
    <div className="space-y-5">{location.state?.lockedFrom&&<p role="status" className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-700 dark:bg-amber-950/30 dark:text-amber-200">{location.state.lockedFrom} is locked while this organization has no valid subscription access. Select a plan or submit payment for Admin review below.</p>}{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</p>}{notice&&<p role="status" className="text-sm text-emerald-700 dark:text-emerald-400">{notice}</p>}
      <section className={panel}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{status?.organizationName||'Organization'}</h2><p className="text-sm">Status: <strong>{status?.state||'Loading'}</strong> · Plan: {status?.plan?.name||'None selected'}</p><p className="text-sm text-slate-500">{status?.state==='TRIALING'?`${days} trial days remaining · ends ${formatDate(status.trialEndsAt,'UTC')}`:status?.state==='GRACE'?`Grace access ends ${formatDate(status.graceEndsAt,'UTC')}`:status?.paidEndAt?`Paid access ends ${formatDate(status.paidEndAt,'UTC')}`:'Select a plan to begin the one-time 14-day trial.'}</p></div><div className="text-sm"><p>Sites {status?.usage?.sites||0}/{status?.plan?.siteLimit??'—'}</p><p>Equipment {status?.usage?.equipment||0}/{status?.plan?.equipmentLimit??'—'}</p><p>Controllers {status?.usage?.controllers||0}/{status?.plan?.controllerLimit??'—'}</p></div></div>{status?.state==='NONE'&&<p className="mt-3 text-amber-700 dark:text-amber-300">Select a plan to start your one-time 14-day trial. No payment proof is required to use the trial.</p>}{status?.state==='SUSPENDED'&&<p className="mt-3 text-red-700 dark:text-red-300">Access suspended: {status.suspensionReason}. An Admin must restore access; payment alone does not remove an administrative suspension.</p>}{status?.state==='GRACE'&&<p className="mt-3 text-amber-700 dark:text-amber-300">Your paid term has ended. Operational access continues only until the grace deadline; submit payment before it expires.</p>}{status?.state==='EXPIRED'&&<p className="mt-3 text-amber-700 dark:text-amber-300">Operational access is paused until an invoice is fully paid and approved.</p>}<Button variant="outline" className="mt-3" onClick={()=>void refresh().catch(()=>setError('Could not check approval status.'))}>Check Approval Status</Button></section>
      <div><h2 className="mb-3 text-lg font-semibold">Available plans</h2>{loading?<p>Loading plans…</p>:!plans.length?<p>No plans are currently available.</p>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{plans.map(plan=><article key={plan.id} className={panel}><h3 className="text-lg font-bold text-[#064789] dark:text-[#8fc7e8]">{plan.name}</h3><p className="mb-3 text-sm text-slate-500">{plan.description}</p><div className="space-y-1 text-sm"><p>Monthly: {plan.currency} {plan.monthly_price}</p><p>Quarterly: {plan.currency} {plan.quarterly_price}</p><p>Annually: {plan.currency} {plan.annual_price}</p><p>Limits: {plan.site_limit} sites · {plan.equipment_limit} equipment · {plan.controller_limit} Controllers</p></div><ul className="my-3 list-inside list-disc text-xs text-slate-600 dark:text-slate-300">{Object.entries(plan.features||{}).filter(([,enabled])=>enabled).map(([key])=><li key={key}>{labels[key]||key}</li>)}</ul><Button disabled={status?.state==='SUSPENDED'} onClick={()=>choice(plan)}>{status?.plan?.code===plan.code?'Renew / Change Cycle':'Select Plan'}</Button></article>)}</div>}</div>
      <BillingWorkspace embedded />
      <ActionModal open={!!selected} title={confirm?'Confirm Plan Selection':'Select Plan'} dirty={false} onClose={()=>{setSelected(null);setConfirm(false);}}><form onSubmit={submit} className="space-y-3 text-sm"><p><strong>{selected?.name}</strong> · {selected?.currency}</p><label className="block">Billing cycle<select className={select} value={cycle} onChange={e=>{setCycle(e.target.value);setRequestKey(crypto.randomUUID());setConfirm(false);}}>{cycles.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><p>Total payable: {selected?.currency} {selected?.[cycles.find(([id])=>id===cycle)?.[2]]}</p><p>Limits: {selected?.site_limit} sites, {selected?.equipment_limit} equipment, {selected?.controller_limit} Controllers.</p><ul className="list-inside list-disc">{Object.entries(selected?.features||{}).filter(([,enabled])=>enabled).map(([key])=><li key={key}>{labels[key]||key}</li>)}</ul>{status?.state==='NONE'&&<p className="text-emerald-700 dark:text-emerald-400">Selecting this plan starts your 14-day trial immediately. Payment proof is not required for the trial.</p>}{status?.state!=='NONE'&&<p>Changing a plan preserves your original trial and paid dates. A different paid plan begins after the current paid period. No mid-cycle proration applies.</p>}{confirm&&<p className="rounded-xl bg-amber-50 p-3 dark:bg-amber-950/30">Confirm creation of a subscription order and invoice. Existing active access continues according to its original dates.</p>}<Button type="submit" loading={busy} disabled={status?.state==='SUSPENDED'}>{confirm?'Confirm Selection':'Continue'}</Button></form></ActionModal>
    </div>
  </PageContainer>;
}
